### ISSUE TITLE
'Driver' does not contain a definition for FindElement

### ISSUE THREAD

**Issue by DanW985** [ElSnoMan/from-scripting-to-framework#14]
Hey,
I have been following your course on TAU as a refresher as haven't coded in a while. It's great simple and effective. I have hit a stumbling block in Chapter 5 "Customizing WebDriver" I am roughly 11 mins into the video and have just performed the dotnet build following the refactoring shown.

After the build I get the following errors (I have included the code it doesn't like);
C:\TAU\scripting-to-framework\Royale\Pages\CardDetailsPage.cs(39,47): error CS0117: 'Driver' does not contain a definition for 'FindElement' [C:\TAU\scripting-to-framework\Royale\Royale.csproj]  
`public IWebElement CardName => Driver.FindElement(By.CssSelector("div[class*='cardName']"));` 
C:\TAU\scripting-to-framework\Royale\Pages\HeaderNav.cs(24,51): error CS0117: 'Driver' does not contain a definition for 'FindElement' [C:\TAU\scripting-to-framework\Royale\Royale.csproj]
`public IWebElement CardsTabLink => Driver.FindElement(By.CssSelector("a[href='/cards']"));`
C:\TAU\scripting-to-framework\Royale\Pages\CardsPage.cs(39,60): error CS0117: 'Driver' does not contain a definition for 'FindElement' [C:\TAU\scripting-to-framework\Royale\Royale.csproj]
`public IWebElement Card(string cardName) => Driver.FindElement(By.CssSelector($"a[href*='{cardName}']"));`
C:\TAU\scripting-to-framework\Royale\Pages\CardDetailsPage.cs(41,51): error CS0117: 'Driver' does not contain a definition for 'FindElement' [C:\TAU\scripting-to-framework\Royale\Royale.csproj]     
`public IWebElement CardCategory => Driver.FindElement(By.CssSelector("div[class*='card__rarity']"));`
C:\TAU\scripting-to-framework\Royale\Pages\CardDetailsPage.cs(43,49): error CS0117: 'Driver' does not contain a definition for 'FindElement' [C:\TAU\scripting-to-framework\Royale\Royale.csproj] 
`public IWebElement CardRarity => Driver.FindElement(By.CssSelector("[class/*='rarityCaption']"));`

I have gone through each file in the repository for chapter 5 and my code matches yours, yet yours builds?

Please help :)

**Comment by ElSnoMan** [comment]
Hi @DanW985,

Could you please provide the code that contains the Driver class definition and where you initialize it? If you have your code hosted on a VCS platform like Github, you can paste the link and I'll check it out 😄

**Comment by DanW985** [comment]
Thanks for getting back to me @ElSnoMan!.

Here is the link to the Git Repo I just created... thought would be easier to give you everything all in one go (y)
https://github.com/DanW985/scripting-to-framework

**Comment by ElSnoMan** [comment]
Let's give this a try and tell me the output:

Change the name of `Pages.cs` to something different like `PageWrapper.cs`

The namespace is called `Pages` and the class is also called `Pages`. That may be giving you problems now that we're at version 5.0 of .NET Core.

**Comment by DanW985** [comment]
@ElSnoMan like a dream thank you! It was irritating me as I couldn't see why it was complaining about the "Driver".. never would have thought it was something to do with a naming conflict. Builds, tests ran and passed. Job done. Can finish the course off now.
Thanks :>
